<?php

namespace AppBundle\Repository;

/**
 * customerUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class customerUserRepository extends \Doctrine\ORM\EntityRepository
{
}
