<?php

namespace AppBundle\Repository;

/**
 * productsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{



    public function selectAll()
    {

        // Build Query
        $results = $this->createQueryBuilder('p')
                        ->select('p.year','p.productImage','p.productName',
                                        'p.salePrice','p.productDescription','p.productArea','p.productCountry')
                        ->getQuery()
                        ->getResult();

        //exit(dump($results));

        // Return Query Results
        return $results;

    }



    public function searchProducts($name)
    {



        $results = $this->createQueryBuilder('products')
                        ->select('products.productName')
                        ->where('products.productName LIKE :name')
                        ->setParameter('name', '%'.$name.'%')
                        ->getQuery()
                        ->getResult();


        return $results;

    }



    public function searchAera($aera)
    {

        $results = $this->createQueryBuilder('p')
                        ->select('p.productArea')
                        ->where('p.productArea LIKE :area')
                        ->setParameter('area',$aera.'%')
                        ->distinct()
                        ->getQuery()
                        ->getResult();


        return $results;

    }








}
