<?php

namespace AppBundle\Repository;

/**
 * WineAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineAreaRepository extends \Doctrine\ORM\EntityRepository
{


    public function findArea()
    {


        $area = $this->createQueryBuilder('a')
                     ->select('a.area')
                     ->getQuery()
                     ->getResult();

        return $area;

    }

}
