<?php

namespace AppBundle\Repository;

/**
 * WinetypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinetypeRepository extends \Doctrine\ORM\EntityRepository
{



    public function findType ()
    {

        $type= $this->createQueryBuilder('w')
                    ->select('w.type','w.imgtype')
                    ->getQuery()
                    ->getResult();

        return $type;

    }


}
